---
title: "Introduction to R/R Studio"
author: "Kyle Suelflow"
format: 
  revealjs:
    smaller: true
    scrollable: true
---


## Goals

Topics we'll cover:

- Installing/loading R packages
- Reading in data
- Cleaning/wrangling data
- Visualizing data

## Setup

1. Open RStudio 

<br>

  -   Open on Desktop if you have it
  -   Open up [rstudio.macalester.edu](rstudio.macalester.edu) and log in with Mac credentials.

2. Download this [template file](Supplementary_Materials/Template.qmd). Save it in a folder called `RStudio_Workshop` on your `Desktop`.

3. Open the file in RStudio 

- Click on the qmd and it will open on the Desktop version.
- Upload the qmd to the RStudio server.

## Quarto Documents

Code + Text (styled with markdown)

Similar to Rmd files

Key Reason to use them: Reproducibility!!

## Introduction to R/R Studio

- Walkthrough of QMD template file
- Feel free to take notes, add things, etc. This is **your** note sheet!
- The link below is to a site with a number of cheatsheets. Super useful

[https://posit.co/resources/cheatsheets/](https://posit.co/resources/cheatsheets/)


